### PR TITLE
Add options to style

### PR DESCRIPTION
**Pull request by srush**
Hi! This library is really amazing. I have wanted something like this for years in python to replace Tikz. 

I started adding some of the functionality from the Haskell Diagrams tutorial. Let me know if this is okay as I keep going. 

I also would love to have the "connections/arrows" part as well. I don't know how hard that would be, but it would be a great extension.

### CODE REVIEW

**Comment by danoneata** [comment]
Hello Sasha! Thanks a lot for the interest and for your suggestions! I would be very happy to add you as a contributor to the project, if you don't mind.

> I started adding some of the functionality from the Haskell Diagrams tutorial. Let me know if this is okay as I keep going.

Sure, feel free to make amendments as you deem necessary! 

> I also would love to have the "connections/arrows" part as well. I don't know how hard that would be, but it would be a great extension.

I agree that having arrows would make a great addition to the project. I remember that it was quite tricky to add them in Haskell's diagrams(see for example [this talk](https://youtu.be/nZCzsBOYdis?t=801)), but maybe we can include a more basic version.

**Comment by srush** [comment]
> Hello Sasha! Thanks a lot for the interest and for your suggestions! I would be very happy to add you as a contributor to the project, if you don't mind.

Sounds great. Let me know the best way to send PRs. 

My goal is to port these diagrams over: https://minitorch.github.io/ . They're really ugly, and I drew them on an ipad. Would love to generate them programmatically. 

> I agree that having arrows would make a great addition to the project. I remember that it was quite tricky to add them in Haskell's diagrams (see for example [this talk](https://youtu.be/nZCzsBOYdis?t=801)), but maybe we can include a more basic version.

Looks really interesting. I'll start with some basic stuff first, and maybe work my way up to that. The library is already more useful than anything I have seen in python.

**Comment by danoneata** [comment]
> Sounds great. Let me know the best way to send PRs.

I've sent you a collaboration invite. I'm fine with whichever collaboration method you prefer (I must admit I'm not very experienced at organizing an open source project): for straightforward changes, you can push into directly into master;
if you think something it's worth discussing, we can have a separate branch and create a pull request.
 
> My goal is to port these diagrams over: https://minitorch.github.io/ . They're really ugly, and I drew them on an ipad. Would love to generate them programmatically.

I see; specifically, for these kind of diagrams I still think tikz trumps, but it would be nice to have an alternative (even if basic) in Python.

> Looks really interesting. I'll start with some basic stuff first, and maybe work my way up to that. The library is already more useful than anything I have seen in python.

Thanks again for the help! What other features (except for the arrows) would you like to see in the project? Maybe I can take a stab at some of those.

**Comment by srush** [comment]
Sounds great.

In my experience there are not too many rules for open source projects. I'll add some Issues for the features I'm working on, and put some others that would be nice to have. Might also add some GitHub CI checks if that is okay with you. Let me know if I overstep.

**Comment by danoneata** [comment]
> I'll add some Issues for the features I'm working on, and put some others that would be nice to have.

Thanks! I'll have a go at implementing support for curves. And I'll follow suite and keep track of the features that I have in mind by creating issues.

> Might also add some GitHub CI checks if that is okay with you.

Sure; please add the CI workflows that you think are suitable.

> Let me know if I overstep.

No worries—it's not the case!

**Pull request merged**
